/* let num = 0
let contagem = ''

while (num <= 50){
    console.log(`numero ${num}`)
    num++
}
 */

/* let  poema = 'voce sabia que o sabia sabia assobiar'
let encontre = poema.includes('carlos')
console.log(encontre) */

/* let num = [1,2,3,4,5,6,7,8,9,10]
    for(let divi = 0; divi < num.length; divi++){
        if(num[divi] % 2 === 0)
        console.log(num[divi])
    } */

/* let pontos = 1500
let usuario = pontos > 1600 ? 'rico' : 'pobre'
console.log(usuario)
 */

function pessoa(nome, sobrenome){
    return{nome, sobrenome}

}
let p1 = pessoa('Carlos', 'araujo')

    console.log(p1)